global:
  imageRegistry: "asia-northeast3-docker.pkg.dev/orderbook-dex-dev/dev-docker-registry"
nameOverride: qa-kaia-orderbook-dex-core
fullnameOverride: qa-kaia-orderbook-dex-core
nodeMode: "full"
nitroNode:
  enabled: true
  image:
    repository: kaia-orderbook-dex-core
    tag: "qa"
    pullPolicy: Always
  resources:
    limits:
      cpu: 4000m
      memory: 16Gi
    requests:
      cpu: 2000m
      memory: 8Gi
  persistence:
    size: 200Gi # Increased for sequencer mode
  # Node selector and tolerations for sequencer pool
  nodeSelector:
    workload: "arbitrum-sequencer"
    node-type: "sequencer"
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "sequencer"
      effect: "NoSchedule"
  args: []
  configFile: "/config/sequencer_config.json"
  # Persistent chain path
  persistentChain: "/data"
  # WASM module root from deployment
  wasmModuleRoot: "0x184884e1eb9fefdc158f6c8ac912bb183bf3cf83f0090317e0bc4ac5860baa39"
  logLevel: 3
  # Enable health check for sequencer mode
  healthCheck:
    enabled: true
  # Staker configuration for full mode
  staker:
    enabled: true
    parentChainWallet:
      privateKey: "0017d1bbc8c2fe03fadb8aabc0284705222e8da8363b98d3502329994f492ba1"
    strategy: "MakeNodes"
    stakerInterval: "30s"
    makeAssertionInterval: "60s"
    confirmationBlocks: 12
    enableFastConfirmation: false
    disableChallenge: false
    dangerous:
      withoutBlockValidator: true
    dataPoster:
      maxMempoolTransactions: 30
    bold:
      enabled: true
      strategy: "MakeNodes"
      rpcBlockNumber: "latest"
      stateProvider:
        checkBatchFinality: false
      parentChainBlockTime: "1s"
      maxGetLogBlocks: 100
      assertionScanningInterval: "60s"
      assertionPostingInterval: "2m"
    parentChainReader:
      useFinality: false
    ensureRollupDeployment: false
  # Inbox reader configuration
  inboxReader:
    readMode: "latest"
  # Ensure rollup deployment is disabled
  ensureRollupDeployment: false
  # Enable dangerous flags for full mode
  dangerousDisableBlobReader: true
  # Validation configuration
  validation:
    blockValidator:
      enable: false
    wasm:
      rootPath: "/data/wasm"
  # Execution configuration
  execution:
    stylusTarget:
      amd64: "x86_64-linux-unknown"
  # Service configuration
  service:
    httpPort: 8547
    wsPort: 8548
  # HTTP API configuration for full mode
  httpApi: "net,web3,eth,debug,arb,arbinternal"
  # Enable GraphQL
  graphql:
    enabled: true
  # Enable pprof for performance profiling
  pprof:
    enabled: true
  # Set replica count
  replicaCount: 1
  env:
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: DD_SERVICE
      value: "kaia-orderbook-dex-core"
    - name: DD_ENV
      value: "qa"
  # Enable ingress for L2 RPC access
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "100m"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      cert-manager.io/cluster-issuer: "letsencrypt-dev"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      # WebSocket support
      nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
      nginx.ingress.kubernetes.io/proxy-set-headers: |
        Upgrade $http_upgrade;
        Connection "upgrade";
    hosts:
      - host: l2-rpc-qa.dexor.trade
        paths:
          - path: /
            pathType: Prefix
            port: http
      - host: l2-ws-qa.dexor.trade
        paths:
          - path: /
            pathType: Prefix
            port: ws
    tls:
      - secretName: l2-rpc-qa-tls
        hosts:
          - l2-rpc-qa.dexor.trade
      - secretName: l2-ws-qa-tls
        hosts:
          - l2-ws-qa.dexor.trade
# QA environment configuration
environment:
  phase: "qa"
  parentChain:
    chainId: 1001 # Kaia Kairos testnet
  # Child chain configuration from deployment
  childChain:
    chainId: 412346
    chainName: "Kaia Orderbook DEX QA"
  # Contract addresses from deployment (QA specific)
  contracts:
    rollup: "0xFe046eA20991fB293d595F849088F209f299d4ea"
    sequencerInbox: "0x0D2E1e580c700a0de43FdB5dAbAe642B9c80BCD9"
    bridge: "0xA26Ff670619228DC0B90D766B40494b5DAa795ae"
    inbox: "0xfdA541dF56d717F2Abc879281d452a99586b305a"
    outbox: "0xa54f39Ab9C60d548bB731790101Fda788040692F"
    rollupEventInbox: "0xbED8ee65DCF27B19Fa6a0c6b06d3b62b76227a72"
    challengeManager: "0xA77F397Fb6d40b982FCEF796490eEF13c7909ab6"
    adminProxy: "0xB6489f2EA810bE16b99F673eB0be54914f8dC6a9"
    upgradeExecutor: "0x011121998801350918727d099bA378dc762398BE"
    validatorWalletCreator: "0x966a477B24abE72Fa7C4a2c9D59FC988E26AACad"
    stakeToken: "0xb8e4feD0ff44BEC05cf2d8E83E499e34483fBFAd"
# Enable monitoring in QA for debugging
monitoring:
  enabled: true
  prometheus:
    port: 6060
# Enable sequencer features
sequencer:
  enabled: true
  coordinatorUrl: "http://0.0.0.0:8547"
  queueSize: 4096 # Queue size for full mode
  maxBlockSpeed: "250ms" # Block speed for full mode
  maxRevertGasReject: 0
  gasCap: "150000000"
  txFeeCap: 10
  delayedSequencer:
    enabled: true
  dangerousNoSequencerCoordinator: true # Required for full mode without redis
  redis:
    enabled: false # Single sequencer in QA
  batchPoster:
    enabled: true # Enable batch posting with private key
    maxDelay: "10s" # Increased from 30s to avoid conflicts with reorg-resistance-margin
    compressionLevel: 6 # 0-9, where 6 is a good balance
    parentChainWallet:
      privateKey: "11d00470a9a385668a65abc1a31a4a349301e5cd8217fdc33fb0eb6c6f971a8e"
    dataPoster:
      maxMempoolTransactions: 20
    dataAvailability:
      enabled: false # Onchain DA for QA
# Nitro specific configuration
nitroConfig:
  feed:
    output:
      enable: true
      port: 9642
# Configuration files for sequencer mode
config:
  generateSequencerConfig: true
  files:
    l2_chain_config.json: |
      {
        "chainId": 412346,
        "homesteadBlock": 0,
        "daoForkSupport": true,
        "eip150Block": 0,
        "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "eip155Block": 0,
        "eip158Block": 0,
        "byzantiumBlock": 0,
        "constantinopleBlock": 0,
        "petersburgBlock": 0,
        "istanbulBlock": 0,
        "muirGlacierBlock": 0,
        "berlinBlock": 0,
        "londonBlock": 0,
        "clique": {
          "period": 0,
          "epoch": 0
        },
        "arbitrum": {
          "EnableArbOS": true,
          "AllowDebugPrecompiles": true,
          "DataAvailabilityCommittee": false,
          "InitialArbOSVersion": 32,
          "InitialChainOwner": "0x99edC6E05eFa0F046d881307ED05955077dbda3c",
          "GenesisBlockNum": 0
        }
      }
    l2_chain_info.json: |
      [
        {
          "chain-name": "arb-dev-test",
          "parent-chain-id": 1001,
          "parent-chain-is-arbitrum": false,
          "sequencer-url": "",
          "secondary-forwarding-target": "",
          "feed-url": "",
          "secondary-feed-url": "",
          "das-index-url": "",
          "has-genesis-state": false,
          "chain-config": {
            "chainId": 412346,
            "homesteadBlock": 0,
            "daoForkSupport": true,
            "eip150Block": 0,
            "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
            "eip155Block": 0,
            "eip158Block": 0,
            "byzantiumBlock": 0,
            "constantinopleBlock": 0,
            "petersburgBlock": 0,
            "istanbulBlock": 0,
            "muirGlacierBlock": 0,
            "berlinBlock": 0,
            "londonBlock": 0,
            "clique": {
              "period": 0,
              "epoch": 0
            },
            "arbitrum": {
              "EnableArbOS": true,
              "AllowDebugPrecompiles": true,
              "DataAvailabilityCommittee": false,
              "InitialArbOSVersion": 32,
              "InitialChainOwner": "0x99edC6E05eFa0F046d881307ED05955077dbda3c",
              "GenesisBlockNum": 0
            }
          },
          "rollup": {
            "bridge": "0xA26Ff670619228DC0B90D766B40494b5DAa795ae",
            "inbox": "0xfdA541dF56d717F2Abc879281d452a99586b305a",
            "sequencer-inbox": "0x0D2E1e580c700a0de43FdB5dAbAe642B9c80BCD9",
            "deployed-at": 192818283,
            "rollup": "0xFe046eA20991fB293d595F849088F209f299d4ea",
            "native-token": "0x0000000000000000000000000000000000000000",
            "upgrade-executor": "0x011121998801350918727d099bA378dc762398BE",
            "validator-wallet-creator": "0x966a477B24abE72Fa7C4a2c9D59FC988E26AACad",
            "stake-token": "0xb8e4feD0ff44BEC05cf2d8E83E499e34483fBFAd"
          }
        }
      ]
    deployment.json: |
      {
        "bridge": "0xA26Ff670619228DC0B90D766B40494b5DAa795ae",
        "inbox": "0xfdA541dF56d717F2Abc879281d452a99586b305a",
        "sequencer-inbox": "0x0D2E1e580c700a0de43FdB5dAbAe642B9c80BCD9",
        "deployed-at": 192818283,
        "rollup": "0xFe046eA20991fB293d595F849088F209f299d4ea",
        "native-token": "0x0000000000000000000000000000000000000000",
        "upgrade-executor": "0x011121998801350918727d099bA378dc762398BE",
        "validator-wallet-creator": "0x966a477B24abE72Fa7C4a2c9D59FC988E26AACad",
        "stake-token": "0xb8e4feD0ff44BEC05cf2d8E83E499e34483fBFAd"
      }
