global:
  imageRegistry: "asia-northeast3-docker.pkg.dev/orderbook-dex-dev/dev-docker-registry"
nameOverride: perf-kaia-orderbook-dex-core
fullnameOverride: perf-kaia-orderbook-dex-core
nodeMode: "full"
nitroNode:
  enabled: true
  image:
    repository: kaia-orderbook-dex-core
    tag: "perf"
    pullPolicy: Always
  resources:
    limits:
      cpu: 4000m
      memory: 16Gi
    requests:
      cpu: 2000m
      memory: 8Gi
  persistence:
    size: 200Gi # Increased for sequencer mode
  # Node selector and tolerations for sequencer pool
  nodeSelector:
    workload: "arbitrum-sequencer"
    node-type: "sequencer"
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "sequencer"
      effect: "NoSchedule"
  args: []
  configFile: "/config/sequencer_config.json"
  # Persistent chain path
  persistentChain: "/data"
  # WASM module root from deployment
  wasmModuleRoot: "0x184884e1eb9fefdc158f6c8ac912bb183bf3cf83f0090317e0bc4ac5860baa39"
  logLevel: 3
  # Enable health check for sequencer mode
  healthCheck:
    enabled: true
  # Staker configuration for full mode
  staker:
    enabled: true
    parentChainWallet:
      privateKey: "b8d4f7607e013d0132424a09645c31c1ac16857ecfce060f7d4d904979e421e0"
    strategy: "MakeNodes"
    stakerInterval: "30s"
    makeAssertionInterval: "60s"
    confirmationBlocks: 12
    enableFastConfirmation: false
    disableChallenge: false
    dangerous:
      withoutBlockValidator: true
    dataPoster:
      maxMempoolTransactions: 30
    bold:
      enabled: true
      strategy: "MakeNodes"
      rpcBlockNumber: "latest"
      stateProvider:
        checkBatchFinality: false
      parentChainBlockTime: "1s"
      maxGetLogBlocks: 100
      assertionScanningInterval: "60s"
      assertionPostingInterval: "2m"
    parentChainReader:
      useFinality: false
    ensureRollupDeployment: false
  # Inbox reader configuration
  inboxReader:
    readMode: "latest"
  # Ensure rollup deployment is disabled
  ensureRollupDeployment: false
  # Enable dangerous flags for full mode
  dangerousDisableBlobReader: true
  # Validation configuration
  validation:
    blockValidator:
      enable: false
    wasm:
      rootPath: "/data/wasm"
  # Execution configuration
  execution:
    stylusTarget:
      amd64: "x86_64-linux-unknown"
  # Service configuration
  service:
    httpPort: 8547
    wsPort: 8548
  # HTTP API configuration for full mode
  httpApi: "net,web3,eth,debug,arb,arbinternal"
  # Enable GraphQL
  graphql:
    enabled: true
  # Enable pprof for performance profiling
  pprof:
    enabled: true
  # Set replica count
  replicaCount: 1
  env:
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: DD_SERVICE
      value: "kaia-orderbook-dex-core"
    - name: DD_ENV
      value: "perf"
    # Performance tuning
    - name: GOMAXPROCS
      value: "4"
    - name: GOGC
      value: "100"
  # Enable ingress for L2 RPC access
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "200m" # Higher for performance testing
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      cert-manager.io/cluster-issuer: "letsencrypt-dev"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      # WebSocket support
      nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
      nginx.ingress.kubernetes.io/proxy-set-headers: |
        Upgrade $http_upgrade;
        Connection "upgrade";
      # Performance optimizations
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
      nginx.ingress.kubernetes.io/worker-connections: "4096"
    hosts:
      - host: l2-rpc-perf.dexor.trade
        paths:
          - path: /
            pathType: Prefix
            port: http
      - host: l2-ws-perf.dexor.trade
        paths:
          - path: /
            pathType: Prefix
            port: ws
    tls:
      - secretName: l2-rpc-perf-tls
        hosts:
          - l2-rpc-perf.dexor.trade
      - secretName: l2-ws-perf-tls
        hosts:
          - l2-ws-perf.dexor.trade
# Performance environment configuration
environment:
  phase: "perf"
  parentChain:
    chainId: 1001 # Kaia Kairos testnet
  # Child chain configuration from deployment
  childChain:
    chainId: 412346 # Will be updated by deployment script
    chainName: "Kaia Orderbook DEX Performance"
  # Contract addresses from deployment (Performance specific - will be updated)
  contracts:
    rollup: "0xcD772f2B5319c15fCB133209C902E8617AFd48ae"
    sequencerInbox: "0xF0111213E64F05CAe88086ddFCD5cb5d5A824dD5"
    bridge: "0xa328448A86402B26289CB6269788138f54AA412a"
    inbox: "0x3a27954BDC87C3Bc2999A2A6B7d2EdAaf2d18875"
    outbox: ""
    rollupEventInbox: ""
    challengeManager: ""
    adminProxy: ""
    upgradeExecutor: "0x24BDc210E5a69bCF61D1b18c08500390a2De03af"
    validatorWalletCreator: "0x33C2aDBF979047445Dbe953d78d6e7B0a3101c89"
    stakeToken: "0xAB12A9a8AEdd9aEEe19fB41b07E3D31bcFc07fc8"
# Enable comprehensive monitoring for performance testing
monitoring:
  enabled: true
  prometheus:
    port: 6060
  metrics:
    enabled: true
    interval: "10s" # More frequent metrics collection
# Performance-optimized sequencer configuration for FULL mode
sequencer:
  enabled: true
  coordinatorUrl: "http://0.0.0.0:8547"
  queueSize: 4096 # Queue size for full mode
  maxBlockSpeed: "250ms" # Block speed for full mode
  maxRevertGasReject: 0
  gasCap: "150000000"
  txFeeCap: 10
  delayedSequencer:
    enabled: true
  dangerousNoSequencerCoordinator: true # Required for full mode without redis
  redis:
    enabled: false # Single sequencer in perf testing
  batchPoster:
    enabled: true
    maxDelay: "10s" # Faster batch posting for full mode
    compressionLevel: 6 # Standard compression level
    parentChainWallet:
      privateKey: "25c4b8e9afe2ff43f27e370087ad842443259734d758b9021ae368415b92a723"
    dataPoster:
      maxMempoolTransactions: 20
  dataAvailability:
    enabled: false # Onchain DA for performance testing
# Performance-optimized Nitro configuration
nitroConfig:
  feed:
    output:
      enable: true
      port: 9642
  http:
    port: 8547
    api: ["eth", "net", "web3", "arb", "debug"] # Enable debug APIs for performance analysis
    cors-domain: "*"
    vhosts: "*"
  ws:
    port: 8548
    api: ["eth", "net", "web3", "arb"]
    origins: "*"
  # Performance tuning
  cache:
    database: 2048 # 2GB cache
    trie: 1024 # 1GB trie cache
    gc: 512 # 512MB GC cache
  txpool:
    locals: ["0x74139D025E36500715DB586779D2c9Ac65da9fF1"]
    nolocals: false
    journal: "transactions.rlp"
    rejournal: "1h"
    pricelimit: 1
    pricebump: 10
    accountslots: 64 # Higher slots for performance testing
    globalslots: 10240 # Higher global slots
    accountqueue: 128
    globalqueue: 5120
# Service configuration with additional ports for monitoring
service:
  main:
    type: ClusterIP
    ports:
      - name: http-rpc
        port: 8547
        targetPort: 8547
      - name: ws-rpc
        port: 8548
        targetPort: 8548
      - name: metrics
        port: 6060
        targetPort: 6060
      - name: feed
        port: 9642
        targetPort: 9642
      - name: pprof
        port: 6061
        targetPort: 6061
# Configuration files for sequencer mode
config:
  generateSequencerConfig: true
  files:
    l2_chain_config.json: |
      {
        "chainId": 412346,
        "homesteadBlock": 0,
        "daoForkSupport": true,
        "eip150Block": 0,
        "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "eip155Block": 0,
        "eip158Block": 0,
        "byzantiumBlock": 0,
        "constantinopleBlock": 0,
        "petersburgBlock": 0,
        "istanbulBlock": 0,
        "muirGlacierBlock": 0,
        "berlinBlock": 0,
        "londonBlock": 0,
        "clique": {
          "period": 0,
          "epoch": 0
        },
        "arbitrum": {
          "EnableArbOS": true,
          "AllowDebugPrecompiles": true,
          "DataAvailabilityCommittee": false,
          "InitialArbOSVersion": 32,
          "InitialChainOwner": "0x34844E6c6C60b590eE54AC5A9183526Eaf376fa6",
          "GenesisBlockNum": 0
        }
      }
    l2_chain_info.json: |
      [
        {
          "chain-name": "arb-dev-test",
          "parent-chain-id": 1001,
          "parent-chain-is-arbitrum": false,
          "sequencer-url": "",
          "secondary-forwarding-target": "",
          "feed-url": "",
          "secondary-feed-url": "",
          "das-index-url": "",
          "has-genesis-state": false,
          "chain-config": {
            "chainId": 412346,
            "homesteadBlock": 0,
            "daoForkSupport": true,
            "eip150Block": 0,
            "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
            "eip155Block": 0,
            "eip158Block": 0,
            "byzantiumBlock": 0,
            "constantinopleBlock": 0,
            "petersburgBlock": 0,
            "istanbulBlock": 0,
            "muirGlacierBlock": 0,
            "berlinBlock": 0,
            "londonBlock": 0,
            "clique": {
              "period": 0,
              "epoch": 0
            },
            "arbitrum": {
              "EnableArbOS": true,
              "AllowDebugPrecompiles": true,
              "DataAvailabilityCommittee": false,
              "InitialArbOSVersion": 32,
              "InitialChainOwner": "0x34844E6c6C60b590eE54AC5A9183526Eaf376fa6",
              "GenesisBlockNum": 0
            }
          },
          "rollup": {
            "bridge": "0xa328448A86402B26289CB6269788138f54AA412a",
            "inbox": "0x3a27954BDC87C3Bc2999A2A6B7d2EdAaf2d18875",
            "sequencer-inbox": "0xF0111213E64F05CAe88086ddFCD5cb5d5A824dD5",
            "deployed-at": 193272684,
            "rollup": "0xcD772f2B5319c15fCB133209C902E8617AFd48ae",
            "native-token": "0x0000000000000000000000000000000000000000",
            "upgrade-executor": "0x24BDc210E5a69bCF61D1b18c08500390a2De03af",
            "validator-wallet-creator": "0x33C2aDBF979047445Dbe953d78d6e7B0a3101c89",
            "stake-token": "0xAB12A9a8AEdd9aEEe19fB41b07E3D31bcFc07fc8"
          }
        }
      ]
    deployment.json: |
      {
        "bridge": "0xa328448A86402B26289CB6269788138f54AA412a",
        "inbox": "0x3a27954BDC87C3Bc2999A2A6B7d2EdAaf2d18875",
        "sequencer-inbox": "0xF0111213E64F05CAe88086ddFCD5cb5d5A824dD5",
        "deployed-at": 193272684,
        "rollup": "0xcD772f2B5319c15fCB133209C902E8617AFd48ae",
        "native-token": "0x0000000000000000000000000000000000000000",
        "upgrade-executor": "0x24BDc210E5a69bCF61D1b18c08500390a2De03af",
        "validator-wallet-creator": "0x33C2aDBF979047445Dbe953d78d6e7B0a3101c89",
        "stake-token": "0xAB12A9a8AEdd9aEEe19fB41b07E3D31bcFc07fc8"
      }
# Performance testing specific configurations
performance:
  # Load testing support
  loadTesting:
    enabled: true
    maxConnections: 10000
    requestTimeout: "30s"
  # Profiling enabled for performance analysis
  profiling:
    enabled: true
    cpu: true
    memory: true
  # Enhanced logging for performance metrics
  logging:
    level: "info"
    format: "json"
    metrics: true
# Pod security configuration
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
# Container security context
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
# Service account configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""
