apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kaia-orderbook-dex-frontend.fullname" . }}-nginx
  labels:
    {{- include "kaia-orderbook-dex-frontend.labels" . | nindent 4 }}
data:
  default.conf: |
{{ .Values.nginx.serverConfig | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kaia-orderbook-dex-frontend.fullname" . }}-env
  labels:
    {{- include "kaia-orderbook-dex-frontend.labels" . | nindent 4 }}
data:
  env-config.js: |
    window._env_ = {
      VITE_ENV: {{ .Values.environment.phase | quote }},
      VITE_API_URL: {{ .Values.environment.apiUrl | quote }},
      VITE_WS_URL: {{ .Values.environment.wsUrl | quote }}
    };