apiVersion: v2
name: kaia-orderbook-dex-admin
description: A Helm chart for Kaia Orderbook DEX Admin Dashboard
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - kaia
  - dex
  - orderbook
  - admin
  - dashboard
  - nextjs
home: https://github.com/kaiachain/kaia-orderbook-dex-admin
sources:
  - https://github.com/kaiachain/kaia-orderbook-dex-admin
maintainers:
  - name: Kaia Team
    email: dev@kaia.io