apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    clusterName: "dev-gke-cluster"
    site: "datadoghq.com"
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
  features:
    apm:
      enabled: false
    logCollection:
      enabled: true
      containerCollectAll: false
    liveProcessCollection:
      enabled: false
    liveContainerCollection:
      enabled: false
    npm:
      enabled: false
    orchestratorExplorer:
      enabled: false
    prometheusScrape:
      enabled: false
    usm:
      enabled: false
  override:
    nodeAgent:
      tolerations:
        - key: workload
          operator: Equal
          value: sequencer
          effect: NoSchedule
      env:
        - name: DD_LOGS_CONFIG_AUTO_MULTI_LINE_DETECTION
          value: "true"
        - name: DD_CONTAINER_EXCLUDE
          value: "image:.*"
        - name: DD_CONTAINER_INCLUDE
          value: "image:asia-northeast3-docker.pkg.dev/orderbook-dex-dev/.*"
      containers:
        agent:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
    clusterAgent:
      replicas: 1
    clusterChecksRunner:
      replicas: 1
