{{- if .Values.validator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kaia-orderbook-dex-core.fullname" . }}-validator
  labels:
    {{- include "kaia-orderbook-dex-core.validator.labels" . | nindent 4 }}
  {{- with .Values.validator.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.validator.service.type }}
  ports:
    - port: {{ .Values.validator.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.monitoring.enabled }}
    - port: {{ .Values.monitoring.prometheus.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "kaia-orderbook-dex-core.validator.selectorLabels" . | nindent 4 }}
{{- end }}