{{- if .Values.nitroNode.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kaia-orderbook-dex-core.fullname" . }}-nitro
  labels:
    {{- include "kaia-orderbook-dex-core.nitroNode.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "kaia-orderbook-dex-core.fullname" . }}-nitro
  replicas: {{ .Values.nitroNode.replicaCount }}
  selector:
    matchLabels:
      {{- include "kaia-orderbook-dex-core.nitroNode.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "kaia-orderbook-dex-core.nitroNode.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kaia-orderbook-dex-core.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: nitro-node
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "kaia-orderbook-dex-core.nitroNode.image" . }}
          imagePullPolicy: {{ .Values.nitroNode.image.pullPolicy }}
          command: ["/usr/local/bin/nitro"]
          args:
            # Core configuration
            - "--chain.id={{ .Values.environment.childChain.chainId }}"
            - "--parent-chain.id={{ .Values.environment.parentChain.chainId }}"
            - "--parent-chain.connection.url={{ .Values.environment.parentChain.rpcUrl | default "https://public-en-kairos.node.kaia.io" }}"
            - "--chain.info-files=/config/l2_chain_info.json"
            {{- if .Values.nitroNode.persistentChain }}
            - "--persistent.chain={{ .Values.nitroNode.persistentChain }}"
            - "--persistent.global-config={{ .Values.nitroNode.persistentChain }}/config"
            {{- end }}
            # HTTP/WS configuration
            - "--http.addr=0.0.0.0"
            - "--http.port={{ .Values.nitroNode.service.httpPort }}"
            - "--http.vhosts=*"
            - "--http.corsdomain=*"
            - "--ws.addr=0.0.0.0"
            - "--ws.port={{ .Values.nitroNode.service.wsPort }}"
            - "--ws.origins=*"
            # Finality configuration for Kaia
            - "--execution.parent-chain-reader.use-finality-data=false"
            - "--node.parent-chain-reader.use-finality-data=false"
            {{- if not .Values.nitroNode.staker.enabled }}
            # Disable staker when not in full mode
            - "--node.staker.enable=false"
            {{- end }}
            {{- if .Values.nitroNode.args }}
            {{- toYaml .Values.nitroNode.args | nindent 12 }}
            {{- end }}
            {{- if .Values.nitroConfig.archiveMode }}
            - "--node.archive"
            {{- end }}
            {{- if .Values.sequencer.enabled }}
            - "--node.sequencer"
            - "--execution.sequencer.enable"
            - "--node.delayed-sequencer.enable"
            - "--node.delayed-sequencer.use-merge-finality=false"
            - "--execution.rpc.gas-cap={{ .Values.sequencer.gasCap }}"
            - "--execution.rpc.tx-fee-cap={{ .Values.sequencer.txFeeCap }}"
            {{- if .Values.sequencer.redis.enabled }}
            - "--node.seq-coordinator.enable"
            - "--node.seq-coordinator.redis-url={{ .Values.sequencer.redis.url }}"
            - "--node.seq-coordinator.my-url={{ .Values.sequencer.coordinatorUrl }}"
            {{- else }}
            - "--node.dangerous.no-sequencer-coordinator"
            {{- end }}
            {{- end }}
            {{- if .Values.nitroConfig.orderbook.enabled }}
            - "--orderbook.enable"
            - "--orderbook.gas-limit={{ .Values.nitroConfig.orderbook.gasLimit }}"
            {{- end }}
            {{- if .Values.timeboost.enabled }}
            - "--timeboost.enable"
            {{- if .Values.timeboost.auctioneer.enabled }}
            - "--timeboost.auctioneer-redis-url={{ .Values.timeboost.auctioneer.redisUrl }}"
            {{- end }}
            {{- end }}
            {{- if .Values.nitroConfig.feed.output.enable }}
            - "--node.feed.output.enable"
            - "--node.feed.output.port={{ .Values.nitroConfig.feed.output.port }}"
            {{- end }}
            {{- if .Values.nitroConfig.dangerous.noL1Listener }}
            - "--node.dangerous.no-l1-listener"
            {{- end }}
            {{- if .Values.nitroNode.dangerousDisableBlobReader }}
            - "--node.dangerous.disable-blob-reader"
            {{- end }}
            {{- if .Values.nitroNode.wasmModuleRoot }}
            - "--validation.wasm.allowed-wasm-module-roots={{ .Values.nitroNode.wasmModuleRoot }}"
            {{- end }}
            {{- if .Values.sequencer.enabled }}
            - "--execution.sequencer.queue-size={{ .Values.sequencer.queueSize }}"
            - "--execution.sequencer.max-block-speed={{ .Values.sequencer.maxBlockSpeed }}"
            - "--execution.sequencer.max-revert-gas-reject=0"
            {{- end }}
            {{- if .Values.sequencer.batchPoster.enabled }}
            - "--node.batch-poster.enable=true"
            - "--node.batch-poster.max-delay={{ .Values.sequencer.batchPoster.maxDelay }}"
            - "--node.batch-poster.compression-level={{ .Values.sequencer.batchPoster.compressionLevel | default 6 }}"
            - "--node.batch-poster.l1-block-bound=latest"
            {{- if .Values.sequencer.batchPoster.dataAvailability }}
            {{- if .Values.sequencer.batchPoster.dataAvailability.enable }}
            - "--node.data-availability.enable={{ .Values.sequencer.batchPoster.dataAvailability.enable }}"
            {{- end }}
            {{- if .Values.sequencer.batchPoster.dataAvailability.restAggregator }}
            - "--node.data-availability.rest-aggregator.enable={{ .Values.sequencer.batchPoster.dataAvailability.restAggregator.enable }}"
            - "--node.data-availability.rest-aggregator.urls={{ .Values.sequencer.batchPoster.dataAvailability.restAggregator.urls }}"
            {{- end }}
            {{- end }}
            {{- if .Values.sequencer.batchPoster.parentChainWallet.privateKey }}
            - "--node.batch-poster.parent-chain-wallet.private-key={{ .Values.sequencer.batchPoster.parentChainWallet.privateKey }}"
            {{- end }}
            {{- end }}
            {{- if .Values.nitroNode.staker.enabled }}
            - "--node.staker.enable=true"
            {{- if .Values.nitroNode.staker.parentChainWallet.privateKey }}
            - "--node.staker.parent-chain-wallet.private-key={{ .Values.nitroNode.staker.parentChainWallet.privateKey }}"
            {{- end }}
            {{- if .Values.nitroNode.staker.strategy }}
            - "--node.staker.strategy={{ .Values.nitroNode.staker.strategy }}"
            {{- end }}
            {{- if .Values.nitroNode.staker.dangerous.withoutBlockValidator }}
            - "--node.staker.dangerous.without-block-validator"
            {{- end }}
            {{- if .Values.nitroNode.staker.bold.rpcBlockNumber }}
            - "--node.bold.rpc-block-number={{ .Values.nitroNode.staker.bold.rpcBlockNumber }}"
            - "--node.bold.strategy=MakeNodes"
            {{- end }}
            {{- if eq .Values.nitroNode.staker.ensureRollupDeployment false }}
            - "--ensure-rollup-deployment=false"
            {{- end }}
            {{- end }}
            {{- if .Values.monitoring.enabled }}
            - "--metrics"
            - "--metrics-server.addr=0.0.0.0"
            - "--metrics-server.port={{ .Values.monitoring.prometheus.port }}"
            {{- end }}
            {{- if .Values.nitroNode.pprof.enabled }}
            - "--pprof"
            - "--pprof-cfg.addr=0.0.0.0"
            {{- end }}
            {{- if .Values.nitroNode.logLevel }}
            - "--log-level={{ .Values.nitroNode.logLevel }}"
            {{- end }}
            {{- if .Values.nitroNode.graphql.enabled }}
            - "--graphql.enable"
            - "--graphql.vhosts=*"
            - "--graphql.corsdomain=*"
            {{- end }}
            # Additional HTTP API configuration
            - "--http.api={{ .Values.nitroNode.httpApi }}"
          env:
            - name: NITRO_PHASE
              value: {{ .Values.environment.phase | quote }}
            {{- if .Values.environment.contracts.rollup }}
            - name: ROLLUP_ADDRESS
              value: {{ .Values.environment.contracts.rollup | quote }}
            {{- end }}
            {{- if .Values.environment.contracts.sequencerInbox }}
            - name: SEQUENCER_INBOX_ADDRESS
              value: {{ .Values.environment.contracts.sequencerInbox | quote }}
            {{- end }}
            {{- with .Values.nitroNode.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.nitroNode.service.httpPort }}
              protocol: TCP
            - name: ws
              containerPort: {{ .Values.nitroNode.service.wsPort }}
              protocol: TCP
            {{- if .Values.nitroConfig.feed.output.enable }}
            - name: feed
              containerPort: {{ .Values.nitroNode.service.feedPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.monitoring.enabled }}
            - name: metrics
              containerPort: {{ .Values.monitoring.prometheus.port }}
              protocol: TCP
            {{- end }}
          {{- if .Values.nitroNode.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          {{- end }}
          resources:
            {{- toYaml .Values.nitroNode.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
            {{- if or .Values.nitroNode.configFile .Values.config.files }}
            - name: config
              mountPath: /config
              readOnly: true
            {{- end }}
        {{- if .Values.debugSidecar.enabled }}
        - name: debug-sidecar
          image: "{{ .Values.debugSidecar.image.repository }}:{{ .Values.debugSidecar.image.tag }}"
          imagePullPolicy: {{ .Values.debugSidecar.image.pullPolicy }}
          command:
            - sh
            - -c
            - |
              echo "Debug sidecar ready. Main container data accessible at /data"
              echo "This container will keep running even if main container fails"
              echo "Use: kubectl exec -it <pod-name> -c debug-sidecar -- sh"
              while true; do sleep 3600; done
          resources:
            {{- toYaml .Values.debugSidecar.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
            {{- if or .Values.nitroNode.configFile .Values.config.files }}
            - name: config
              mountPath: /config
              readOnly: true
            {{- end }}
        {{- end }}
      {{- with .Values.nitroNode.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nitroNode.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nitroNode.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if or .Values.nitroNode.configFile .Values.config.files }}
        - name: config
          configMap:
            name: {{ include "kaia-orderbook-dex-core.fullname" . }}-config
      {{- end }}
  {{- if .Values.nitroNode.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        {{- with .Values.nitroNode.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          - {{ .Values.nitroNode.persistence.accessMode }}
        storageClassName: {{ include "kaia-orderbook-dex-core.storageClass" . }}
        resources:
          requests:
            storage: {{ .Values.nitroNode.persistence.size }}
  {{- end }}
{{- end }}
