# QA environment overrides for kaia-orderbook-dex-frontend

global:
  imageRegistry: "asia-northeast3-docker.pkg.dev/orderbook-dex-dev/dev-docker-registry"

nameOverride: qa-kaia-orderbook-dex-frontend
fullnameOverride: qa-kaia-orderbook-dex-frontend

replicaCount: 1

image:
  repository: kaia-orderbook-dex-frontend
  tag: "dev"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dev"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    # WebSocket support
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/upgrade: "$http_upgrade"
    nginx.ingress.kubernetes.io/connection: "$connection_upgrade"
  hosts:
    - host: qa.dexor.trade
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: qa-dexor-trade-tls
      hosts:
        - qa.dexor.trade

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 64Mi

autoscaling:
  enabled: false

env:
  - name: DD_AGENT_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: DD_SERVICE
    value: "kaia-orderbook-dex-frontend"
  - name: DD_ENV
    value: "qa"

# Environment configuration
environment:
  phase: "qa"
  apiUrl: "https://api-qa.dexor.trade/api/v1"
  wsUrl: "wss://api-qa.dexor.trade/ws"

# Build-time environment variables
buildEnv:
  VITE_ENV: "qa"
  VITE_API: "https://api-qa.dexor.trade/api/v1"

# ServiceAccount
serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: "kaia-dex-frontend-sa@orderbook-dex-dev.iam.gserviceaccount.com"
  name: "qa-kaia-dex-frontend"

# Pod Disruption Budget
podDisruptionBudget:
  enabled: false  # Disable for QA environment

# Extra volumes for nginx configuration
extraVolumes: []

extraVolumeMounts: []

# Monitoring
monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
    namespace: "monitoring"
    interval: 30s
    scrapeTimeout: 10s
