apiVersion: v2
name: kaia-orderbook-dex-backend
description: A Helm chart for Kaia Orderbook DEX Backend services
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - kaia
  - dex
  - orderbook
  - blockchain
home: https://github.com/kaiachain/kaia-orderbook-dex-backend
sources:
  - https://github.com/kaiachain/kaia-orderbook-dex-backend
maintainers:
  - name: Kaia Team
    email: dev@kaia.io