# QA environment overrides for kaia-orderbook-dex-backend
# Inherits most settings from dev, with QA-specific database configurations

global:
  imageRegistry: "asia-northeast3-docker.pkg.dev/orderbook-dex-dev/dev-docker-registry"

nameOverride: qa-kaia-orderbook-dex-backend
fullnameOverride: qa-kaia-orderbook-dex-backend

# API Service Configuration
api:
  replicaCount: 1

  image:
    repository: kaia-orderbook-dex-backend/api-app
    tag: "qa"

  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
    wsPort: 9090
    wsTargetPort: 9090

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-dev"
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"
      # CORS support
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "https://qa.dexor.trade"
      nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
      nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
      # WebSocket support
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    hosts:
      - host: api-qa.dexor.trade
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: api-qa-dexor-trade-tls
        hosts:
          - api-qa.dexor.trade

  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

  env:
    - name: KAIA_ORDERBOOK_PHASE
      value: "qa"
    - name: CONFIG_FILE
      value: "/app/config/qa.toml"
    - name: DD_ENV
      value: "qa"
# Event Service Configuration
event:
  replicaCount: 1

  image:
    repository: kaia-orderbook-dex-backend/event-app
    tag: "qa"

  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

  env:
    - name: KAIA_ORDERBOOK_PHASE
      value: "qa"
    - name: CONFIG_FILE
      value: "/app/config/qa.toml"
    - name: DD_ENV
      value: "qa"

# ServiceAccount
serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: "kaia-dex-backend-sa@orderbook-dex-dev.iam.gserviceaccount.com"
  name: "kaia-dex-backend-qa"

# Pod Disruption Budget
podDisruptionBudget:
  enabled: false  # Disable for QA environment
  minAvailable: 1

# Network Policy
networkPolicy:
  enabled: false  # Disable for QA environment

# Monitoring
monitoring:
  enabled: false  # Disable until monitoring stack is installed
  serviceMonitor:
    enabled: false
    namespace: "monitoring"
    interval: 30s
    scrapeTimeout: 10s

environment:
  phase: "qa"
