apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kaia-orderbook-dex-backend.fullname" . }}-config
  labels:
    {{- include "kaia-orderbook-dex-backend.labels" . | nindent 4 }}
data:
  dev.toml: |
{{ .Files.Get "config/dev.toml" | indent 4 }}
  qa.toml: |
{{ .Files.Get "config/qa.toml" | indent 4 }}
  perf.toml: |
{{ .Files.Get "config/perf.toml" | indent 4 }}