{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kaia-orderbook-dex-backend.fullname" . }}-api
  labels:
    {{- include "kaia-orderbook-dex-backend.api.labels" . | nindent 4 }}
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kaia-orderbook-dex-backend.api.selectorLabels" . | nindent 4 }}
{{- end }}