apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-kaia-orderbook-dex-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # ArgoCD Image Updater configuration
    argocd-image-updater.argoproj.io/image-list: frontend=asia-northeast3-docker.pkg.dev/orderbook-dex-dev/dev-docker-registry/kaia-orderbook-dex-frontend:dev
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/pull-secret: pullsecret:kaia-dex/gcr-secret
spec:
  project: default
  source:
    repoURL: git@github.com:probepark/dexor-charts.git
    targetRevision: HEAD
    path: charts/kaia-orderbook-dex-frontend
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kaia-dex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m