apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-kaia-orderbook-dex-core
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # ArgoCD Image Updater configuration
    argocd-image-updater.argoproj.io/image-list: nitroNode=asia-northeast3-docker.pkg.dev/orderbook-dex-dev/dev-docker-registry/kaia-orderbook-dex-core:dev
    argocd-image-updater.argoproj.io/nitroNode.update-strategy: digest
    argocd-image-updater.argoproj.io/nitroNode.helm.image-name: nitroNode.image.name
    argocd-image-updater.argoproj.io/nitroNode.helm.image-tag: nitroNode.image.tag
spec:
  project: default
  source:
    repoURL: https://github.com/kaiachain/kaia-orderbook-dex-devops
    targetRevision: HEAD
    path: charts/kaia-orderbook-dex-core
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kaia-dex
  syncPolicy:
    # Automated sync disabled for core component
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
