apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-sql-proxy
  annotations:
    iam.gke.io/gcp-service-account: cloud-sql-proxy-sa@${PROJECT_ID}.iam.gserviceaccount.com
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-proxy
spec:
  selector:
    app: cloud-sql-proxy
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-sql-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-sql-proxy
  template:
    metadata:
      labels:
        app: cloud-sql-proxy
    spec:
      serviceAccountName: cloud-sql-proxy
      containers:
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4
        args:
          - "--private-ip"
          - "--address=0.0.0.0"
          - "--port=3306"
          - "${CONNECTION_NAME}"
        ports:
        - containerPort: 3306
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL